stages:
 - deploy
services:
  - docker:dind
image: docker
# before_script:
#   - apk add --update py-pip
#   - pip install docker-compose
deploy:
  stage: deploy
  # variables:
  #   - SIGNALMASTER_URL: $SIGNALMASTER_URL
  #   - RIFF_SERVER_URL: $RIFF_SERVER_URL
  #   - MYSQL_URL: $MYSQL_URL
  #   - MM_SQLSETTINGS_DATASOURCE: $MM_SQLSETTINGS_DATASOURCE
  script:
    - mkdir $DOCKER_CERT_PATH
    - echo "$CA" > $DOCKER_CERT_PATH/ca.pem
    - echo "$CLIENT_CERT"
    - echo "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
    - ls -alh certs
    - docker build --build-arg MATTERMOST_SERVER_REPO=$MM_SERVER_REPO  -t riffedu-webapp .
    - docker run  -it -e MM_SQLSETTINGS_DATASOURCE=$MM_SQLSETTINGS_DATASOURCE -e RIFF_SERVER_URL=$RIFF_SERVER_URL -e SIGNALMASTER_URL=$SIGNALMASTER_URL --expose=8065 riffedu-webapp
    - rm -rf $DOCKER_CERT_PATH
  only:
    - feature/CI-gitlab
  variables:
    DOCKER_TLS_VERIFY: "1"
    DOCKER_HOST: "tcp://$INSTANCE_IP:2376"
    DOCKER_CERT_PATH: "certs"
  tags:
    - docker
