stages:
 - deploy
services:
  - docker:dind
image: docker
before_script:
  - apk add --update py-pip
  - pip install docker-compose
deploy:
  stage: deploy
  variables:
    - SIGNALMASTER_URL: $SIGNALMASTER_URL
    - RIFF_SERVER_URL: $RIFF_SERVER_URL
    - MYSQL_URL: $MYSQL_URL
    - MM_SQLSETTINGS_DATASOURCE: $MM_SQLSETTINGS_DATASOURCE
  script:
    - mkdir $DOCKER_CERT_PATH
    - echo "$CA" > $DOCKER_CERT_PATH/ca.pem
    - echo "$CLIENT_CERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$CLIENT_KEY" > $DOCKER_CERT_PATH/key.pem
    - docker-compose build
    - docker-compose down
    - docker-compose up -d --force-recreate
    - rm -rf $DOCKER_CERT_PATH
  only:
    - feature/CI-gitlab
  variables:
    DOCKER_TLS_VERIFY: "1"
    DOCKER_HOST: "tcp://$INSTANCE_IP:2376"
    DOCKER_CERT_PATH: "certs"
  tags:
    - docker
