image: node:10

before_script:
    # setting unsafe-perm and shell config is needed to get the mattermost-redux
    # dependency correctly installed BECAUSE it is a git url w/ a prepare script
    # AND the node image user is root! npm acts differently when run as root!
    - npm config set unsafe-perm true
    - npm config set shell /bin/bash

check-style:
    stage: test
    script:
        - make check-style-ci
    only:
        - merge_requests
        - tags
        - /gitlab/

test:
    stage: test
    script:
        - make test-ci
    only:
        - merge_requests
        - tags
        - /gitlab/

build:
    stage: test     # test rather than build, as it doesn't need to complete before testing
    script:
        - make build
    only:
        - merge_requests
        - tags
        - /gitlab/
