image: node:10

check-style:
    stage: test
    script:
        - make check-style
    only:
        - merge_requests
        - tags
        - /gitlab/

test:
    stage: test
    script:
        - make test
    only:
        - merge_requests
        - tags
        - /gitlab/

build:
    stage: test     # test rather than build, as it doesn't need to complete before testing
    script:
        - make build
    only:
        - merge_requests
        - tags
        - /gitlab/
