image: node:10

# Cache modules in between jobs (caching setup copied from https://docs.gitlab.com/ee/ci/caching/index.html)
# Use specific job cache settings to allow 1 setup job to push, and all other jobs to pull
#cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#        - node_modules/

stages:
    - setup
    - test
    - deploy

before_script:
    # setting unsafe-perm and shell config is needed to get the mattermost-redux
    # dependency correctly installed BECAUSE it is a git url w/ a prepare script
    # AND the node image user is root! npm acts differently when run as root!
    - npm config set unsafe-perm true
    - npm config set shell /bin/bash

npm-install:
    stage: setup
    script:
        - npm install
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - node_modules/

check-style:
    stage: test
    script:
        - make check-style-ci THRESHOLD=1830
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - node_modules/
    artifacts:
        when: always
        paths:
            - build/check-style.log.html
    only:
        - merge_requests
        - tags
        - /gitlab/

test:
    stage: test
    script:
        - make test-ci
        - tail --lines=14 build/test.log
    allow_failure: true
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - node_modules/
    artifacts:
        when: always
        paths:
            - build/test.log
            - build/test-results.xml
    only:
        - merge_requests
        - tags
        - /gitlab/

build:
    stage: test     # test rather than build, as it doesn't need to complete before testing
    script:
        - make build > build/build.log
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        policy: pull
        paths:
            - node_modules/
    artifacts:
        when: always
        paths:
            - build/build.log
    only:
        - merge_requests
        - tags
        - /gitlab/
