image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE/riffedu-webapp:$CI_COMMIT_SHA
  BUILD_IMAGE_TAG: $CI_REGISTRY_IMAGE/build:latest
  ECR_BUILD_IMAGE_TAG: $ECR_REPOSITORY_URL/build:latest
  ECR_IMAGE_TAG: $ECR_REPOSITORY_URL:$CI_COMMIT_SHA
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
before_script:
  - apk add --no-cache curl jq python py-pip
  - pip install awscli

build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $BUILD_IMAGE_TAG || true
    - docker build --build-arg MATTERMOST_SERVER_REPO=$MM_SERVER_REPO --build-arg RIFF_SERVER_URL=$RIFF_SERVER_URL --build-arg SIGNALMASTER_URL=$SIGNALMASTER_URL --build-arg MM_SQLSETTINGS_DATASOURCE=$MM_SQLSETTINGS_DATASOURCE -t $BUILD_IMAGE_TAG --cache-from $BUILD_IMAGE_TAG .
    - docker push $BUILD_IMAGE_TAG
    - docker build --build-arg MATTERMOST_SERVER_REPO=$MM_SERVER_REPO --build-arg RIFF_SERVER_URL=$RIFF_SERVER_URL --build-arg SIGNALMASTER_URL=$SIGNALMASTER_URL --build-arg MM_SQLSETTINGS_DATASOURCE=$MM_SQLSETTINGS_DATASOURCE -t $IMAGE_TAG  --cache-from $IMAGE_TAG --cache-from $BUILD_IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - docker

test:
  stage: test
  script:
    - make test
  only:
    - feature/CI_gitlab

.deploy_review:
  stage: deploy
  image: coxauto/aws-ebcli
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
  script:
    - echo $AWS_ACCESS_KEY_ID
    - ./deploy.sh
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://riffedu-webapp-$CI_ENVIRONMENT_SLUG.us-west-2.elasticbeanstalk.com
    on_stop: stop_review
  only:
    - branches
  except:
    - master

.stop_review:
  stage: deploy
  image: coxauto/aws-ebcli
  variables:
    GIT_STRATEGY: none
  script:
    - eb init riffedu-webapp -r us-west-2 -p docker-17.09.1-ce
    - eb terminate --force "$CI_ENVIRONMENT_SLUG" | tee "$CIRCLE_ARTIFACTS/eb_deploy_output.txt"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master
  when:
    manual

.deploy:
  stage: deploy
  image: coxauto/aws-ebcli
  script:
    - ./deploy.sh
  environment:
    name: development
    url: http://riffedu-webapp-dev.us-west-2.elasticbeanstalk.com
  only:
    - master
